/**
 * @param {string} cmid
 * @param {string} canvaswidth
 * @param {string} canvasheight
 */
export const init = (cmid, canvaswidth, canvasheight) => {
    //window.addEventListener("resize", function () {
    //if (canvaswidth > getWidth()) {
    const resizer = document.getElementById("unilabeltype-imageboard-resizer-"+cmid);
    resizer.addEventListener("click", function () {

            const imageboard = document.getElementById("unilabeltype-imageboard-"+cmid);
            let newcanvaswidth = 0;
            if (getWidth() < 750) {
                newcanvaswidth = (getWidth() - imageboard.getBoundingClientRect().left)-10;
            } else if (getWidth() < 585) {
                newcanvaswidth = (getWidth() - imageboard.getBoundingClientRect().left)-20;
            } else {
                newcanvaswidth = (getWidth() - imageboard.getBoundingClientRect().left)-80;
            }

            if (newcanvaswidth > canvaswidth) {
                newcanvaswidth = canvaswidth ;
            }

            let widthfactor = newcanvaswidth / canvaswidth;
            //const mydiv = document.getElementById("module-"+cmid);
            const mydiv = document.getElementById("unilabeltype-imageboard-"+cmid);

            mydiv.style.transform = "scale("+widthfactor+")";
            mydiv.style.transformOrigin = "0 0";

            // The height of the white space that is generated by scaling the div can be calculated
            let heightOfSpace = canvasheight * (1 - widthfactor);
            mydiv.style.marginBottom = "-" + heightOfSpace + "px";
    });

    // Add eventlistener that toggles the 50x50px helpergrid on and off
    const gridtoggler = document.getElementById("unilabeltype-imageboard-gridtoggler-"+cmid);
    gridtoggler.addEventListener("click", function () {
        const helpergrid = document.getElementById("unilabeltype-imageboard-helpergrid-"+cmid);
        if ( helpergrid.classList.contains("hidden")) {
            helpergrid.classList.remove("hidden");
            gridtoggler.value = 'gridvisible';
            gridtoggler.innerText = 'hide #';
        } else {
            helpergrid.classList.add("hidden");
            gridtoggler.value = 'gridhidden';
            gridtoggler.innerText = 'show #';
        }
    });
};


/**
 * Helper function to get the width of the usable browserarea.
 *
 * @returns {*|number}
 */
function getWidth() {
    if (self.innerWidth) {
        return self.innerWidth;
    }
    if (document.documentElement && document.documentElement.clientWidth) {
        return document.documentElement.clientWidth;
    }
    if (document.body) {
        return document.body.clientWidth;
    }
}
